### ISSUE TITLE
Let me build only one lambda

### ISSUE THREAD

**Issue by dchelimsky** [StediInc/lambda#7]
`clj -m stedi.lambda.build` builds all the entry point fns it finds. For development, I'd like a means of only building the one(s) I want so I don't have to wait for the one(s) I don't care about to build.

**Comment by tvanhens** [comment]
How would you expect this to work? Default to building all and then optionally take a comma separated list of individual lambdas to build?

**Comment by dchelimsky** [comment]
Definitely default to building all. I care less abou the details of the override, though a comma separated list is a perfectly good option.
